#!/bin/sh
# Runs both test suites and regenerates COVERAGE.md from what they measured.
#
# The report is generated rather than written by hand, and it is regenerated by the same
# command that runs the tests, because a coverage figure that has to be refreshed by a
# separate step is a figure that goes stale. Run it through `make test`.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)

echo "==> backend"
(cd "$root/backend" && go test -race -coverprofile=coverage.out ./...)
(cd "$root/backend" && go tool cover -html=coverage.out -o coverage.html)

echo "==> front end"
frontend_log=$(mktemp)
trap 'rm -f "$frontend_log"' EXIT

set +e
(cd "$root/frontend" && pnpm coverage >"$frontend_log" 2>&1)
frontend_status=$?
set -e

cat "$frontend_log"

# A report written after a failing run would state coverage for code that does not work.
if [ "$frontend_status" -ne 0 ]; then
    echo "front-end tests failed; COVERAGE.md left untouched" >&2
    exit "$frontend_status"
fi

{
    echo "# Coverage report"
    echo
    echo "Generated by \`make test\`, which runs both suites and rewrites this file from what"
    echo "they measured. Do not edit it by hand."
    echo
    echo "Which layer is tested and why is explained in the README, under Testing and coverage."
    echo "The same run writes browsable HTML to \`backend/coverage.html\`, and CI uploads both"
    echo "profiles as build artifacts."
    echo
    echo "## Backend"
    echo
    echo '```'
    (cd "$root/backend" && go tool cover -func=coverage.out)
    echo '```'
    echo
    echo "## Front end"
    echo
    echo '```'
    sed -n '/^ *File/,/^-\{10,\}$/p' "$frontend_log" | sed 's/[[:space:]]*$//'
    echo '```'
} >"$root/COVERAGE.md"

echo "==> COVERAGE.md updated"
