#!/bin/sh
# Regenerates COVERAGE.md from both test suites.
#
# The report is generated rather than written by hand because hand-written coverage figures
# drift the moment a test is added, and a stale number is worse than no number. Run it
# through `make cover`.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)

(cd "$root/backend" && go test -race -coverprofile=coverage.out ./... >/dev/null)
(cd "$root/backend" && go tool cover -html=coverage.out -o coverage.html)

frontend_report=$(cd "$root/frontend" && pnpm coverage 2>&1 || true)

{
    echo "# Coverage report"
    echo
    echo "Generated by \`make cover\`. Regenerate it after changing tests; do not edit by hand."
    echo
    echo "Which layer is tested and why is explained in the README, under Testing and coverage."
    echo "The same command writes browsable HTML to \`backend/coverage.html\`, and CI uploads"
    echo "both profiles as build artifacts."
    echo
    echo "## Backend"
    echo
    echo '```'
    (cd "$root/backend" && go tool cover -func=coverage.out)
    echo '```'
    echo
    echo "## Front end"
    echo
    echo '```'
    printf '%s\n' "$frontend_report" | sed -n '/^ *File/,/^-\{10,\}$/p' | sed 's/[[:space:]]*$//'
    echo '```'
} >"$root/COVERAGE.md"

echo "wrote COVERAGE.md"
